### ISSUE TITLE
Feedback from Morgan and Diane

### ISSUE THREAD

**Issue by msschwartz21** [dlmbl/image_translation#1]
- [ ] Please add more hints to the tasks. It will help get students going in the right direction faster.
- [ ] Capitalize section titles for style :)
- [ ] Add learning goals to each checkpoints
- [ ] For checkpoints 3 and 4, separate the questions into a separate question box
- [ ] For section 5, clarify that the entire section is a bonus section and add blue boxes to the tasks.

---
Universal tasks
- [ ] Update environment setup to use `mamba` (See https://github.com/dlmbl/DL-MBL-2023/wiki/Exercise-Guidelines#environment)
- [ ] Add a red callout block to the beginning of each notebook that specifies which kernel to use
```
<div class="alert alert-danger">
Please use kernel <kernel name here>
</div>
```
- [ ] Check for any references to slack. We are going to use Element this year.

**Comment by edyoshikun** [comment]
closing this issue as we are writing new notebook.
